sonar.projectKey=blog-pessoal-dotnet
sonar.projectName=Blog Pessoal Backend ASP.NET Core
sonar.host.url=http://localhost:9000
sonar.token=sqp_b49d46d834d172dbeff235241e5cc98275a27a01
sonar.sourceEncoding=UTF-8
sonar.sources=.